#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout
yabai -m config layout bsp

# Mouse
yabai -m config mouse_follows_focus off

# Padding and gaps
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     0

# Window modifications
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m config window_border_blur off
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0X7FE78A4E

# Prevent yabai from managing certain apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

echo "yabai configuration loaded.."
