#!/usr/bin/env sh

# Global settings
yabai -m config layout                      bsp
yabai -m config window_placement            second_child
yabai -m config window_topmost              off
yabai -m config window_shadow               float
yabai -m config window_opacity              off
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9

# Signal that scripting-addition was loaded successfully (if it was)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Prevent yabai from managing certain apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

echo "yabai configuration loaded.."
